import type { GameManifest } from '@kids-games-zone/shared';

export const gameRegistry: GameManifest[] = [
  {
    id: 'dummy-game',
    name: 'Click Counter',
    description: 'Click the button 5 times!',
    thumbnail: '',
    ageRange: [3, 12],
    skills: ['motor_skills'],
    version: '1.0.0',
    entryPoint: '../../games/dummy-game/src/index.ts',
    minDifficulty: 1,
    maxDifficulty: 1,
    estimatedPlayTime: 1,
    offlineCapable: true,
    status: 'beta',
    releaseDate: '2026-03-15',
    tags: ['demo'],
  },
  {
    id: 'math-adventure',
    name: 'Math Adventure',
    description: 'Solve math problems and sharpen your number skills!',
    thumbnail: '/images/games/math-adventure.webp',
    ageRange: [6, 8],
    skills: ['numeracy'],
    version: '1.0.0',
    entryPoint: '../../games/math-adventure/src/index.ts',
    minDifficulty: 1,
    maxDifficulty: 5,
    estimatedPlayTime: 5,
    offlineCapable: true,
    status: 'active',
    releaseDate: '2026-03-16',
    tags: ['math', 'addition', 'subtraction', 'multiplication'],
  },
  {
    id: 'word-puzzle',
    name: 'Word Puzzle',
    description: 'Unscramble the letters to spell the word!',
    thumbnail: '/images/games/word-puzzle.webp',
    ageRange: [6, 8],
    skills: ['literacy'],
    version: '1.0.0',
    entryPoint: '../../games/word-puzzle/src/index.ts',
    minDifficulty: 1,
    maxDifficulty: 5,
    estimatedPlayTime: 5,
    offlineCapable: true,
    status: 'active',
    releaseDate: '2026-03-16',
    tags: ['spelling', 'words', 'vocabulary', 'literacy'],
  },
  {
    id: 'memory-match',
    name: 'Memory Match',
    description: 'Find the matching pictures and train your memory!',
    thumbnail: '/images/games/memory-match.webp',
    ageRange: [3, 5],
    skills: ['memory'],
    version: '1.0.0',
    entryPoint: '../../games/memory-match/src/index.ts',
    minDifficulty: 1,
    maxDifficulty: 5,
    estimatedPlayTime: 3,
    offlineCapable: true,
    status: 'active',
    releaseDate: '2026-03-16',
    tags: ['memory', 'matching', 'pairs', 'animals'],
  },
];
