import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { runAudioGeneration } from './generate-audio.js';
import {
  EncouragementPlanSchema,
  type EncouragementPlan,
} from './encouragement-plan.js';
import { ManifestSchema, type Manifest } from './manifest.js';

export interface EncouragementRunOptions {
  repoRoot: string;
  planPath: string;
  cacheDir: string;
  lockPath: string;
  registryPath: string;
  force: boolean;
  dryRun: boolean;
}

export interface EncouragementRunSummary {
  generated: number;
  cached: number;
  totalChars: number;
  estimatedUsd: number;
  variants: number;
  registryPath: string;
}

export async function runEncouragementGeneration(
  opts: EncouragementRunOptions,
): Promise<EncouragementRunSummary> {
  const plan = await loadEncouragementPlan(opts.planPath);
  const langShort = plan.lang.split('-')[0]!;
  const outputDir = plan.outputDir.replace('{langShort}', langShort);

  const phrases = plan.entries.flatMap((entry) =>
    entry.texts.map((text, i) => ({
      id: `${entry.baseId}-${i + 1}`,
      text,
      rate: 1.0,
    })),
  );

  const manifest: Manifest = ManifestSchema.parse({
    name: 'encouragement',
    lang: plan.lang,
    provider: plan.provider,
    voice: plan.voice,
    outputDir,
    phrases,
  });

  const audioSummary = await runAudioGeneration({
    repoRoot: opts.repoRoot,
    manifests: [manifest],
    cacheDir: opts.cacheDir,
    lockPath: opts.lockPath,
    force: opts.force,
    dryRun: opts.dryRun,
  });

  if (!opts.dryRun) {
    await writeVariantRegistry(opts.registryPath, plan, langShort);
  }

  return {
    ...audioSummary,
    variants: phrases.length,
    registryPath: opts.registryPath,
  };
}

async function loadEncouragementPlan(
  path: string,
): Promise<EncouragementPlan> {
  const raw = JSON.parse(await readFile(path, 'utf8'));
  return EncouragementPlanSchema.parse(raw);
}

async function writeVariantRegistry(
  registryPath: string,
  plan: EncouragementPlan,
  langShort: string,
): Promise<void> {
  const variants: Record<string, string[]> = {};
  for (const entry of plan.entries) {
    variants[entry.baseId] = entry.texts.map(
      (_t, i) => `${entry.baseId}-${i + 1}`,
    );
  }

  const body = [
    '// AUTO-GENERATED by tools/audio-generator — do not edit by hand.',
    '// Regenerate with: pnpm --filter @kids-games-zone/audio-generator audio:encouragement',
    '',
    'import type { VoiceVariants } from \'../services/audio-manager\';',
    '',
    'export const voiceVariants: VoiceVariants = {',
    `  '${langShort}': ${JSON.stringify(variants, null, 2)
      .split('\n')
      .join('\n  ')},`,
    '};',
    '',
  ].join('\n');

  await mkdir(dirname(resolve(registryPath)), { recursive: true });
  await writeFile(resolve(registryPath), body, 'utf8');
}
